sudo: required
services:
  - docker

before_install:
  - docker build -t ruthyramani/docker -f Dockerfile.dev .

script:
  - docker run ruthyramani/docker npm rum test -- --coverage

install: travis_wait 30 mvn install