version: '3'
services:
  reactapp:
    build:
      context: /home/kali/Desktop/Docker_world/my-nodejs-project/my-react-app                      
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #- /app/node_modules
      #- /app:/app
      - /home/kali/Desktop/Docker_world/my-nodejs-project/my-react-app:/app
                                       
  #tests:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.dev
   # volumes:
   #   - /app/node_modules
   #   - .:/app
   # command: ["npm", "run", "test"]

